version: '3.8'
services:
  localstack:
    image: localstack/localstack  # Docker image for LocalStack
    container_name: LGC_Code_Challenge_LocalStack
    ports:
      - "4566:4566"  # Expose the gateway port
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LOCALSTACK_DOCKER_HOST=unix:///var/run/docker.sock
      - SERVICES=dynamodb  # Specify the LocalStack services to run
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"  # Allow LocalStack to access Docker
    
